### ISSUE TITLE
Building MSI: Invalid Product Version

### ISSUE THREAD

**Issue by DavidZidar** [clowd/Clowd.Squirrel#100]
I'm trying out Clowd.Squirrel and I'm hitting an issue with Wix when trying to create an MSI package. It does not like my rather large version numbers that represent build dates.

The exact same issue was previously reported to Squirrel.Windows as Squirrel/Squirrel.Windows#916 and solved in PR Squirrel/Squirrel.Windows#1023

Here's what the error output looks like:
```
[INFO] Program: Compiling machine-wide msi deployment tool in 64-bit mode

[ERRO] System.AggregateException: One or more errors occurred. (Failed to compile WiX template, command invoked was: 'candle.exe -nologo -ext WixNetFxExtension -out C:\code\projects\myapp\artifacts\Publish\MyAppSetup.wixobj C:\code\projects\myapp\artifacts\Publish\MyAppSetup.wxs'

Output was:
MyAppSetup.wxs
C:\code\projects\myapp\artifacts\Publish\MyAppSetup.wxs(3) : error CNDL0242 : Invalid product version '1.8238.33358.0'. Product version must have a major version less than 256, a minor version less than 256, and a build version less than 65536.)
 ---> System.Exception: Failed to compile WiX template, command invoked was: 'candle.exe -nologo -ext WixNetFxExtension -out C:\code\projects\myapp\artifacts\Publish\MyAppSetup.wixobj C:\code\projects\myapp\artifacts\Publish\MyAppSetup.wxs'

Output was:
MyAppSetup.wxs
C:\code\projects\myapp\artifacts\Publish\MyAppSetup.wxs(3) : error CNDL0242 : Invalid product version '1.8238.33358.0'. Product version must have a major version less than 256, a minor version less than 256, and a build version less than 65536.
   at Squirrel.HelperExe.CompileWixTemplateToMsi(String wxsTarget, String outputFile) in ./Internal/HelperExe.cs:line 101
   at SquirrelCli.Program.createMsiPackage(String setupExe, IPackage package, Boolean packageAs64Bit) in ./Program.cs:line 439
   --- End of inner exception stack trace ---
   at SquirrelCli.Program.Releasify(ReleasifyOptions options)
   at SquirrelCli.CommandAction`1.Execute(IEnumerable`1 args) in ./ValidatedOptionSet.cs:line 168
   at SquirrelCli.Program.Main(String[] args) in ./Program.cs:line 87
```

I understand that you might not want to change this now that you are working on a complete rewrite but I thought I'd report it anyway.

**Comment by caesay** [comment]
I'm still planning on supporting 2.x as I understand some people may not want to update. Are you using v2.9.42? 

I had a look at the [PR you linked](https://github.com/Squirrel/Squirrel.Windows/pull/1023/files), could you make this same change to your local copy of Squirrel and verify that it fixes the issue? You can find `template.wxs` in the Squirrel tools folder, probably in `%userprofile%\.nuget\packages`.

**Comment by caesay** [comment]
I am also curious what the output of that !bind command will be as I'm not very familiar with WiX, presumably it's just `version % 256`?

**Comment by DavidZidar** [comment]
Yes, I am using v2.9.42. I just tried the workaround and it created an MSI but it does not seem to be working in Windows Sandbox at least. A window pops up that says something like "Windows configures the deployment tool" but then it quickly disappears and nothing else happens.

I see, that does seem like an ugly hack. Hmm, for my purposes I don't even care about the version number on the MSI package itself, if I could pass an alternate version string with an argument like `--msi-version 1.0.0.0` or something that would be fine by me.

**Comment by caesay** [comment]
After some consideration I won't be accepting the `!bind` trick, because finding workarounds to do things that are officially unsupported is not something I want to encourage nor something I would trust to work consistently.

I think the temptation with a separate flag would be to do what you suggested (eg. `--msi-version 1.0.0.0`) for every build, and not properly increment the MSI version string. This means the generated MSI's are actually un-deployable through an enterprise deployment scenario using group policy etc which depends on the version number incrementing. Additionally you now will have to track somewhere which MSI version corresponds to which app version, and it also requires an extra command line argument in Squirrel for a niche use-case.

Anyone who depends on MSI's working correctly absolutely must pick consistently incrementing version numbers where the major/minor part are less than 256, and in this case it's desirable for the product version to align with this. I won't be making any changes to Squirrel at this time unless there is a better suggestion.

**Comment by caesay** [comment]
As a personal work-around, if you wish to do this in your own project, you can edit the `template.wxs` in any way you choose, including overwriting the `Version` parameter with a hard-coded `1.0.0.0` rather than the correct version.

**Comment by DavidZidar** [comment]
I won't be changing my perfectly good version numbers just because of MSI. 😄 That said I agree with your reasoning.

Is there a way to provide a path to an alternate `wsx`-file that I'm missing? Editing the file under `.nuget/packages` is a no go. I suppose I could just call candle myself though.

**Comment by caesay** [comment]
I think if you drop a `template.wxs` file in the current working directory Squirrel should find it instead of the included one but I've not tested this.
