### ISSUE TITLE
Possible to install ASP.NET core Runtime?

### ISSUE THREAD

**Issue by cupper1** [clowd/Clowd.Squirrel#123]
Hi All,
Stupid question maybe, but my app requires ASP.NET Core Runtime 6.0.x. When running the installer, it successfully handles the net6 install but then when starting it complains it needs .net 6. 
I traced this back to needing ASP.NET Core Runtime, once I install that on a clean Virtual Machine, my app runs just fine. 

Thanks!

**Comment by caesay** [comment]
Hi, this is not currently possible - Squirrel only supports bootstrapping the WindowsDesktop runtime. I would recommend you ship your app as self-contained. Since Squirrel supports delta updates, updates will remain fast!

**Comment by osnoser1** [comment]
Hi, I have a desktop application running with dotnet 6.0, but recently I added an internal asp net core in the startup, when I send the update the startup fail, I wouldn't like to ship the app as a self contained because the installer grow up a lot, is there a way to show to the user a dialog alerting to download the asp net core runtime? Or specify a custom url to download the installer? 

Thank you very much in advance.
