### ISSUE TITLE
Squirrel.exe in the app directory after installation

### ISSUE THREAD

**Issue by RyusukeFujita** [clowd/Clowd.Squirrel#19]
I'm testing with version `2.7.34-pre` and I found that `Squirrel.exe` remains in the application directory.
When I was using version `2.6.34-pre`, `Squirrel.exe` didn't exist after installation (only `Update.exe` in the directory above). 
\* I am aware that `Squirrel.exe` has been in the full nupkg files before 2.7.*

My understanding is that `Update.exe` and `Squirrel.exe` are exactly the same (I checked that their file hash match), and maybe `Squirrel.exe` is renamed to `Update.exe` after installation/update.  

Not a super big deal, but both `Squirrel.exe` & `Update.exe` occupy around 12 MB for a .NET 6.0 app and having these large files duplicated seems a bit wasteful to me.  

Do we really need both `Squirrel.exe` & `Update.exe`?
Or am I doing something wrong?

Thanks

**Comment by caesay** [comment]
You're correct that in my version, `Squirrel.exe` (just the same as `Update.exe`) is bundled into each release (full and a diff in deltas) and it is copied on-top of the `Update.exe` during updates, so we can keep `Update.exe` up to date with your app as I ship new Squirrel versions.

The network overhead is ~7.5mb (compressed) when downloading the initial setup & full package, and basically nothing after that (because of delta updates). But it does get extracted and duplicated on disk, as you've seen. 

There are a couple of reasons we can't delete the extra copy inside your application directory:

1. The `Squirrel.exe` binary is running during updates (it copies itself on top of `Update.exe` once everything else has exited) - so it can not be reliably deleted during an update. 
2. Squirrel.exe is used to apply a diff and update Update.exe on the next version of your app. Example: 
     - Your app 1.0 installed
     - Squirrel.exe copies itself to Update.exe
     - Later, you are installing a 1.1-delta update
     - During the delta update, Squirrel.exe is copied and the delta patch is applied to create Squirrel.exe-1.1 (just the same as any other file with a diff)
     - New 1.1 version of Squirrel.exe copies itself to Update.exe again
 
Update.exe is needed in the root dir for obvious reasons, and if Squirrel.exe was missing from your app directory, the next delta update would fail and your app would need to download a whole new full release.

**Comment by RyusukeFujita** [comment]
Thanks for the detailed explanation, @caesay!
I understand.

I appreciate your effort on this repo.
