### ISSUE TITLE
Rollback and previous version

### ISSUE THREAD

**Issue by alucard2876** [clowd/Clowd.Squirrel#196]
Hello, I have a question related to rollbacks. Can we somehow change a version to lower or manually download  previous releases and apply them?

**Comment by caesay** [comment]
At the moment, this is not possible. I am working on an update to v3, which may make this possible. For now, if you wish to roll all of your users back to a previous version, you must re-publish your older version as a newer version.

**Comment by Denisjc** [comment]
This makes CI/CD very hard as the rollout of the version is controlled by the build server and stored there
So to have a deployment process that is controllable with specific versions  is very important.
So we should be able at any moment to roll forward and roll back in the deployment.

**Comment by caesay** [comment]
Hi @Denisjc, I'm not sure exactly I understand what you mean. 

1. If you are working automated via CI, such as reverting commits after discovering a bug, each new CI build will have an incrementing version number and be greater than the version before it, and you will not run into this issue. 
2. If you are looking to remove a release once it's been deployed, so that your users will stop getting it as an update, you can do this manually by removing the line from your RELEASES file wherever it is that you deploy releases. 

The part that is not currently possible, is _via your installed application_, explicitly choosing to install a version which is < the currently installed version. This _explicit_ rollback via client code will be possible in the next version of Squirrel, but it won't be automated. 

If you would like to explain your scenario in more detail, I might be able to consider it when implementing new features in the future.
