### ISSUE TITLE
Replace WebClient with HttpClient in FileDownloader

### ISSUE THREAD

**Issue by simader** [clowd/Clowd.Squirrel#20]
Hi Casey, 

 warning SYSLIB0014: 'WebClient.WebClient()' is obsolete: 'WebRequest, HttpWebRequest, ServicePoint, and WebClient are obsolete. Use HttpClient instead.'

Do you have any plans to remove the WebClient und use HttpClient in FileDownloader.cs instead?

Best,
Andreas

**Comment by caesay** [comment]
I will leave `FileDownloader` as-is, accepting a WebClient (for backwards compatibility) but it is on my list to create a `HttpClientFileDownloader` class which will be used by default. Also, the `Utility.CreateWebClient()` function should return a `HttpClientFileDownloader` instead of a `WebClient`.

**Comment by caesay** [comment]
Would also accept a PR if you are willing to look at it

**Comment by caesay** [comment]
This is now released [in 2.7.79](https://github.com/clowd/Clowd.Squirrel/releases/tag/2.7.79-pre).
