### ISSUE TITLE
Clowd.Squirrel.props file exclusion

### ISSUE THREAD

**Issue by domyd** [clowd/Clowd.Squirrel#26]
In [this commit](https://github.com/clowd/Clowd.Squirrel/commit/225ffcc5e635a3c8128b88977305e43bec251ae4#diff-e6406dd753376708a91424ab2f329d67ddf06707016497f233264b0a37fab4cb), you removed the `Clowd.Squirrel.props` file from the nuget package. What were the reasons for this?

I'm currently migrating a project away from Squirrel.Windows, and the `SquirrelToolsPath` property that it exposes is quite important to me. Would it be possible to re-include it?

**Comment by caesay** [comment]
Hi and thanks for checking out this repository. Yes, it's possible to re-include for the next release, I only removed it initially because it was not working properly in my tests and I didn't bother to spend the time to try and investigate the issue. I will take a look and see if I can get this working again, in the mean time, if you notice any obvious issues it would be appreciated.

**Comment by caesay** [comment]
I am not sure what my problem was initially, but I have added this back (762d0087f4406f1f8b007a19fb477ecece0e51ba) and it is working fine, so it will be in the next release.

**Comment by chm-tm** [comment]
From my understanding, this `.props` file is only used for backward compatibility. New projects can use the [`GeneratePathProperty` metadatum](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#generatepathproperty) on the Squirrel `PackageReference` instead.

**Comment by caesay** [comment]
This is now released [in 2.7.79](https://github.com/clowd/Clowd.Squirrel/releases/tag/2.7.79-pre).
