### ISSUE TITLE
404 when downloading RELEASES from private github repo

### ISSUE THREAD

**Issue by Mat-Stevenson-Simworx** [clowd/Clowd.Squirrel#50]
I have been trying to get the GithubUpdateManager working with a private github repo. After some investigating it looks like personal access tokens only with with github api calls and calls to github.com will fail. See [here ](https://github.com/afragen/git-updater/issues/475)for a simular issue. 

I have been trying to fix the issue myself but feel like i am going down a path of significant rework. I though it would make more sense to talk it out incase i have just missed something simple. 

The root of the issue is [here](https://github.com/clowd/Clowd.Squirrel/blob/02323d972fdd2b1feca3a1a9256a841c878b89a3/src/Squirrel/UpdateManager.CheckForUpdates.cs#L80). There is a missing access token plus the url is to the browser url where it looks like it needs to be the api asset url. Something like https://api.github.com/repos/{org}/{repo}/releases/assets/{asset_id}. The accept header also needs to be `application/octet-stream` otherwise you will get a json response. 

I feel like to get this method to work we would need to add some kind of abstraction layer for interfacing with the files that make up a release. Maybe the IFileDownloader is a good place to do this kind of work.

**Comment by caesay** [comment]
Looks like this would be a great improvement! 

I've been unravelling UpdateManager recently a little, it used to be all sealed internal however it needs more work. I think that the key logic in UpdateManager should be broken out into sensible protected virtual functions so that GithubUpdateManager (or something else) can override. For example, a `protected virtual void DownloadAsset(string name)` function would allow the GithubUpdateManager to iterate the assets in a release and get the appropriate download url. 

Happy to accept a PR with something like this, but it might end up being quite large, as you mentioned - probably not the easiest first issue. I may be able to look at this in a few weeks time if there is no PR before then.

**Comment by Mat-Stevenson-Simworx** [comment]
Great. I ll see what I can put together. Whats your feelings on how the currently UpdateManager is made up of a few sub classes? Like [CheckForUpdateImpl ](https://github.com/clowd/Clowd.Squirrel/blob/02323d972fdd2b1feca3a1a9256a841c878b89a3/src/Squirrel/UpdateManager.CheckForUpdates.cs#L14)and [DownloadReleasesImpl](https://github.com/clowd/Clowd.Squirrel/blob/02323d972fdd2b1feca3a1a9256a841c878b89a3/src/Squirrel/UpdateManager.DownloadReleases.cs#L12).

**Comment by caesay** [comment]
I don't like the sub-classes personally, they're a carry over from the old Squirrel. I'd love to extract the relevant functionality in those private classes into appropriate protected virtual functions of UpdateManager

**Comment by caesay** [comment]
This is released in [2.9.3-g5eac3d](https://github.com/clowd/Clowd.Squirrel/releases/tag/2.9.3-g5eac3d).
