### ISSUE TITLE
Options to Configure/Hide the installer progress

### ISSUE THREAD

**Issue by adamhewitt627** [clowd/Clowd.Squirrel#56]
My project is switching from Squirrel, and has already incorporated a spinner (using GIF) into our installer splash image. This is jarring with the green progress bar.

While the progress bar is great, can we either:
1. Hide it entirely.
2. Change its color to fit with the company branding.

**Comment by caesay** [comment]
Hi Adam, thanks for your feedback and for trying this fork! 

A GIF does not do a good job of showing progress, which is especially important when installing big programs on slow computers or downloading new runtimes (can take a very long time). Green is also the standard/default progress bar colour for windows, it's what used in all the native progress bars including the progress bars that appear over task bar icons.

I'm not yet personally convinced that this needs to be colour-configurable (or removable), mainly because if every little thing was configurable in Squirrel, the command line would be 10 pages long! I might be willing to consider a change of some kind if you can provide me with a screenshot of how the splash screen looks for your use-case.

If this is a deal breaker for you, as a workaround you can compile `Update.exe` yourself and replace the pre-compiled one in the packages you create. [The progress bar rendering code is here](https://github.com/clowd/Clowd.Squirrel/blob/develop/src/Update/Windows/User32SplashWindow.cs#L291).

**Comment by adamhewitt627** [comment]
Thanks for the response, you hit all the points that I told my client. I like the bar, they just aren't convinced. We're about to start a rebrand of it anyway, so I think it will mostly be a moot point.

I'll keep the fork option in mind, though. Thanks again!

**Comment by caesay** [comment]
One alternative idea would be to use some heuristic to determine the optimal progress bar colour based on the colours at the bottom of the splash image, but I doubt it would satisfy everybody :) Feel free to re-open this if you have anything to add.
