### ISSUE TITLE
Update brings warning in command line

### ISSUE THREAD

**Issue by xmln17** [clowd/Clowd.Squirrel#77]
I recently updated Squirrel in my application and I got this warning:
![Screenshot_CLI](https://user-images.githubusercontent.com/55558686/168658686-293495d7-e51a-4f9f-b835-1f9f011a3312.png)

Does the message appear because I have not updated the nuget package correctly or for some other reason? My app still updated successfully. Can I ignore this message in the future or should I update Squirrel in some specific way?

**Comment by caesay** [comment]
This message is because you are using version 2.9.39 of the nuget package but using version 3.9.40 of Squirrel.exe. You should use the same version in the nuget package and for Squirrel.exe - as we update things here there may be incompatibility that causes apps to break if you do not use the same version for creating releases and in nuget.
