### ISSUE TITLE
Help me to add consent window

### ISSUE THREAD

**Issue by nazar322** [clowd/Clowd.Squirrel#87]
I need to add a consent window to the Squirrel installer in order to comply with the [AVG clean guidelines](https://support.avg.com/SupportArticleView?l=en&urlname=AVG-Threat-Lab-clean-guideline).
Basically, I need to display a dialog with hyperlinks to my ToS, EULA, and Privacy Policy and a user must have two options, either Agree and continue installation or Cancel.

I understand that for this task the source code must be modified but I'm new to this project and therefore I'd like to ask you for a hint on where and how it can be implemented nicely.

I could go with the hardcoded window, it's not a universal solution and will require modifying the window for every project I build an installer for, but this will work for my project and it's the only thing I can come up with.

So my idea is to create my custom consent window under the `Windows` directory in `Update.Windows` project and then display it somewhere before the installation process ever begins.
At the beginning of `executeCommandLine` seems to be a fine place for this, however, if the user chooses to cancel installation the proper cleanup should take place, and here I'm not sure what should be called for proper cleanup. 

Is there some method/s I can call to properly clean up installation, such as removing already extracted resources? Or how can I do it manually?

If you have better ideas of how this can be implemented please share! :)

**Comment by caesay** [comment]
If you are looking to modify Squirrel, you may wish to fork and work on the `master` branch rather than the `develop` branch, as the former is stable and the latter is not yet.

To address some of your points specifically:

> Basically, I need to display a dialog with hyperlinks to my ToS, EULA, and Privacy Policy and a user must have two options, either Agree and continue installation or Cancel.

You could save yourself some time have your EULA on your website before Setup.exe is downloaded.

> I could go with the hardcoded window, it's not a universal solution and will require modifying the window for every project I build an installer for, but this will work for my project and it's the only thing I can come up with.

You could store additional information in the nuspec file (look at `ZipPackage.cs`) to make a EULA accept window more reusable. 

> Is there some method/s I can call to properly clean up installation, such as removing already extracted resources? Or how can I do it manually?

Setup.exe is a small binary that extracts Update.exe and runs it. When Update.exe exits, it is deleted (cleaned up) by Setup.exe automatically. Update.exe should always return exit code 0 unless there is an error, because if the exit code is not zero an error dialog will be shown to the user by Setup.exe.


The full approach might be something like this:
- Add options to Update.exe (like '--eulaLink', '--privatePolicyLink' etc)
- Store those options into nuspec using `ZipPackage.cs`
- If those options are present when installing (eg. in the `Setup` method of Update.exe, after the nuspec is loaded) show a EULA accept window.
- If declined, exit immediately with code 0. 
- If accepted, continue the `Setup` method normally.

**Comment by nazar322** [comment]
@caesay  Sounds good to me! Thanks for your points!
